[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
poll_site = "8WtoeFycM6CribYGy1URCYBrUg9XNMYBsqbewNY3xggr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/darius/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
